name: build

on:
  push:
    branches: [ main, mall-cloud-alibaba ]
  pull_request:
    branches: [ main, mall-cloud-alibaba ]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./mall-cloud-alibaba-master

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 1) Build con Java 8
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8

      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

      - name: Build project
        run: mvn -B clean verify -DskipTests

      # 2) Switch a Java 11 (o 17) per SonarCloud
      - name: Set up JDK 11 for SonarCloud
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Run SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B sonar:sonar \
            -Dsonar.projectKey=AlessandroMessa_Tesi \
            -Dsonar.organization=alessandromessa \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${SONAR_TOKEN}