name: build

on:
  push:
    branches:
      - main
      - mall-cloud-alibaba
  pull_request:
    branches:
      - main
      - mall-cloud-alibaba

jobs:
  build-and-analyze:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java 8 & cache Maven
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '8'
          cache: maven

      - name: Build with Maven
        run: mvn -B clean package -T1C -DskipTests

      - name: Setup Java 21 for SonarQube
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: Run SonarQube analysis
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN:    ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar ^
            -Dsonar.projectKey=mall-cloud-alibaba ^
            -Dsonar.host.url=${{ env.SONAR_HOST_URL }} ^
            -Dsonar.login=${{ env.SONAR_TOKEN }}